name       : gnome-remote-desktop
version    : '44.2'
release    : 10
source     :
    - https://download.gnome.org/sources/gnome-remote-desktop/44/gnome-remote-desktop-44.2.tar.xz : 7a9ffd341b5fcb636d26675e9f6269650952163fff5295327618cc2d5cc87b8e
homepage   : https://gitlab.gnome.org/GNOME/gnome-remote-desktop
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Remote desktop daemon for GNOME using pipewire
description: |
    Remote desktop server which allows you to connect to your machine remotely.
builddeps  :
    - pkgconfig(fdk-aac)
    - pkgconfig(ffnvcodec)
    - pkgconfig(freerdp2)
    - pkgconfig(fuse3)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libnotify)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libsecret-1)
    - pkgconfig(libvncclient)
    - pkgconfig(tss2-esys)
    - asciidoc
setup      : |
    %meson_configure \
        -Dsystemd=true \
        -Dvnc=true \
        -Drdp=true \
        -Dsystemd_user_unit_dir=%libdir%/systemd/user/
build      : |
    %ninja_build
install    : |
    %ninja_install
