name       : gnome-remote-desktop
version    : '41.2'
release    : 4
source     :
    - https://download.gnome.org/sources/gnome-remote-desktop/41/gnome-remote-desktop-41.2.tar.xz : 10151e69b648c2247c5e33d9a2ef419f4e037ee5b2bae49e6ed6aca77eb1ba58
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Remote desktop server which allows you to connect to your machine remotely
description: |
    Remote desktop server which allows you to connect to your machine remotely
builddeps  :
    - pkgconfig(freerdp2)
    - pkgconfig(fuse3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libsecret-1)
    - pkgconfig(libvncclient)
setup      : |
    %meson_configure -Dnvenc=false -Dsystemd_user_unit_dir=%libdir%/systemd/user/
build      : |
    %ninja_build
install    : |
    %ninja_install
