name       : gnome-remote-desktop
version    : '41.0'
release    : 2
source     :
    - https://download.gnome.org/sources/gnome-remote-desktop/41/gnome-remote-desktop-41.0.tar.xz : 6a9bc8b1c68746f4a3aac1fe74c44a72e26a8bb4be1f1ca73027705acb652b5e
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Remote desktop server which allows you to connect to your machine remotely
description: |
    Remote desktop server which allows you to connect to your machine remotely
builddeps  :
    - pkgconfig(freerdp2)
    - pkgconfig(fuse3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libsecret-1)
    - pkgconfig(libvncclient)
setup      : |
    %meson_configure -Dnvenc=false -Dsystemd_user_unit_dir=%libdir%/systemd/user/
build      : |
    %ninja_build
install    : |
    %ninja_install
