name       : gnome-remote-desktop
version    : '42.3'
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-remote-desktop/42/gnome-remote-desktop-42.3.tar.xz : a296ad58f8b3bdac0e2e0d87db12a9395e72770a960e787fbcc1be3f0068b642
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Remote desktop server which allows you to connect to your machine remotely
description: |
    Remote desktop server which allows you to connect to your machine remotely
builddeps  :
    - pkgconfig(ffnvcodec)
    - pkgconfig(freerdp2)
    - pkgconfig(fuse3)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libnotify)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libsecret-1)
    - pkgconfig(libvncclient)
setup      : |
    %meson_configure -Dsystemd=true -Dvnc=true -Drdp=true -Dsystemd_user_unit_dir=%libdir%/systemd/user/
build      : |
    %ninja_build
install    : |
    %ninja_install
